name: "Static Analysis"
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
jobs:
  Static-Check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - uses: jfrog/.github/.github/actions/install-go-with-cache

      - uses: jfrog/.github/.github/actions/gosec-scanner

  Go-Sec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - uses: jfrog/.github/.github/actions/install-go-with-cache

      - name: Run Gosec Security Scanner
        # Temporarily set version 2.18.0 to workaround https://github.com/securego/gosec/issues/1046
        uses: securego/gosec@v2.18.0
        with:
          args: -exclude G204,G301,G302,G304,G306 -tests -exclude-dir \.*test\.* ./...
